/// <reference types="@electron-forge/plugin-vite/forge-vite-env" />

declare global {
  // This allows TypeScript to pick up the magic constants that are auto-generated by Forge's Vite
  // plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
  // whether you're running in development or production).

  const RENDER_VITE_DEV_SERVER_URL: string;
  const RENDER_VITE_NAME: string;

  interface ImportMetaEnv {
    readonly VITE_NATIVE_DIR: string | undefined;
  }

  interface ImportMeta {
    readonly env: ImportMetaEnv;
  }
}

export {}; // Make this a module
